### ISSUE TITLE
test_boundaries_to_extent fails with PROJ 5.0.0

### ISSUE THREAD

**Issue by sebastic** [pytroll/mpop#49]
As reported in [Debian Bug #892462](https://bugs.debian.org/892462), `test_boundaries_to_extent` fails since the update of [PROJ to version 5.0.0](https://raw.githubusercontent.com/OSGeo/proj.4/5.0.0/NEWS):
```
======================================================================
FAIL: test_boundaries_to_extent (mpop.tests.test_satin_helpers.TestSatinHelpers)
Test conversion of area boundaries to area extent.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mpop/tests/test_satin_helpers.py", line 194, in test_boundaries_to_extent
    correct_values_afgh[i], 2)
AssertionError: 0.0 != 3053894.9120028536 within 2 places
```

CC: @avalentino

**Comment by davidh-ssec** [comment]
@sebastic I'm not familiar with debugging debian builds so maybe you or @avalentino could help me a little bit. This utility method and all of the projection parts of mpop use the `pyproj` library which uses the PROJ4 C library underneath. So my guess would be that if mpop is failing in this unit test then the `pyproj` package should also be failing. Do you have any idea if that is true?

IIRC correctly pyproj can build against an internal copy of the PROJ4 C library if it doesn't detect a system PROJ4 C library. My guess is that the pyproj debian package is built depending on the C library package and should be changed to require "PROJ4 C <5". These are all guesses, but I'm hoping this can help someone to the right answer.

**Comment by sebastic** [comment]
The five tests for pyproj succeeded with PROJ 5.0.0, see:
[python-pyproj → 1.9.5.1-3+b2 → amd64  buildlog](https://buildd.debian.org/status/fetch.php?pkg=python-pyproj&arch=amd64&ver=1.9.5.1-3%2Bb2&stamp=1520217124&raw=0)

The pyproj Debian package is indeed built with the system library, but it won't be changed to use the internal copy.

mpop/mipp/pyresample needs to be updated to work correctly with PROJ 5.0.0, or if this is a regression in PROJ 5.0.0 this needs to be fixed in its the next release. For the latter we need a test case the reproduce the issue, ideally a `cs2cs` command that works correctly with PROJ 4.9.3 but fails with PROJ 5.0.0 in the same way as this test case.

**Comment by davidh-ssec** [comment]
@sebastic Understood and agreed. I am not an original developer of mpop, but I've looked at the source for these tests and what they call and this doesn't seem like it can possibly be mpop's fault (I know, wishful thinking from a developer). Mpop has no direct connection to the PROJ C library and simply calls the `pyproj.Proj` object for coordinate transformation.

@mraspaud @pnuu @adybbroe Do any of you have a debian system you can test this stuff on? If we take the input data points and projections from the test that is failing I would expect it to fail with the PROJ command line tool or in pyproj by itself.

**Comment by pnuu** [comment]
I have Ubuntu system (based on Debian), but I'm running LTS 16.04 version, which still has PROJ 4.9.2-2. I'll see if I can update one of my older laptops to a version with PROJ 5.x tomorrow to test more.

**Comment by sebastic** [comment]
You can use `debootstap` to create a Debian unstable chroot, or use [cowbuilder](https://pkg-grass.alioth.debian.org/policy/packaging.html#git-pbuilder) for the same build chroots used for Debian package builds.

Full fledged VMs are another option.

**Comment by avalentino** [comment]
the issue seems to be related to a change in the behaviour of proj5 in case of invalid results:
* proj4 seems to mark invalid result by setting them to 1e30
* proj5 set invalid results to 0

python-mpop check for invalid values and replaces them with nans

https://github.com/pytroll/mpop/blob/98b32ca1b1db6f0e3236fbc8dbcaa0f21d14c456/mpop/satin/helper_functions.py#L115-L118

this check of curse does not detects invalid values in generated by proj5.

Adding a new check against zero seems to fix the unit test but I don't know it this is an acceptable fix in the general case.

Is the management of invalid results documented somewhere in proj?

**Comment by pnuu** [comment]
After two dist upgrades: there's no PROJ 5.0.0 in Ubuntu 17.10. Could've checked that beforehand.

Invalid values are set to zero? That's a valid projection coordinate value. I'm quite certain that will break a lot of applications if that's really the case. Quick look at PROJ.4 (both 4.x and 5.0.0) source code indicates that HUGE_VAL from math.h is used for invalid values, and current pyproj (which includes PROJ 4.9.3 C source code) also defines invalid values as HUGE_VAL in _proj.pyx Cython interface.

**Comment by davidh-ssec** [comment]
@avalentino Have you been able to find that as a documented feature/change of PROJ? Or are you stating that that's what seems to be happening? If the latter then I agree, but I also agree with @pnuu that I hope that is not what PROJ 5 intended because 0 is a valid coordinate value.

**Comment by avalentino** [comment]
> @avalentino Have you been able to find that as a documented feature/change of PROJ?

no, no, I just reported what I can observe when I dump values during the test execution.
In one case (proj 4) I see some of the values at 1e30, in the other case (proj5) I see the same values set to 0 (zero).

I absolutely don't know if this is an intended behaviour, that is why I asked for a link to the relevant documentation.

**Comment by sebastic** [comment]
[Error handling](http://proj4.org/development/errorhandling.html) is not documented, your best bet is to contact the [PROJ developers](http://lists.maptools.org/mailman/listinfo/proj).

CC: @kbevers

**Comment by kbevers** [comment]
PROJ should not return 0 for invalid values. Please provide an example call to `cs2cs` or `cct` that demonstrates what is happening so I can have a look at why this happens.

I think you meant to say

> Error handling is not documented **yet**, your best bet is to contact the PROJ developers.

:-). For now there is [this](http://proj4.org/development/reference/functions.html#error-reporting) though which should help a bit.

**Comment by avalentino** [comment]
An example
Proj4 on ubuntu 17.10

```
$ proj
Rel. 4.9.3, 15 August 2016
usage: proj [ -bCeEfiIlormsStTvVwW [args] ] [ +opts[=arg] ] [ files ]

$ echo 85.05493299 46.52610743 | proj +proj=geos +lon_0=0.00 +lat_0=0.00 +a=6378169.00 +b=6356583.80 +h=35785831.00
*	*
```


Proj5 on debian sid

```
$ proj
Rel. 5.0.0, March 1st, 2018
usage: proj [ -beEfiIlormsStTvVwW [args] ] [ +opts[=arg] ] [ files ]

$ echo 85.05493299 46.52610743 | proj +proj=geos +lon_0=0.00 +lat_0=0.00 +a=6378169.00 +b=6356583.80 +h=35785831.00
0.00	0.00
```

**Comment by kbevers** [comment]
Fixed in https://github.com/OSGeo/proj.4/pull/857. Will be available in a few weeks when 5.0.1 is released.

**Comment by mraspaud** [comment]
@kbevers Thanks for the fast reaction !

Should be close the issue @sebastic ?

**Comment by sebastic** [comment]
I'm going to cherry-pick the changes into the proj Debian package to verify that it fixes this issue.

**Comment by sebastic** [comment]
The test now succeeds with the changes from https://github.com/OSGeo/proj.4/pull/857:
```
test_boundaries_to_extent (mpop.tests.test_satin_helpers.TestSatinHelpers)
Test conversion of area boundaries to area extent. ... /build/python-mpop-1.5.0/mpop/satin/helper_functions.py:125: RuntimeWarning: All-NaN axis encountered
  extent = [np.nanmin(x_dir),
/build/python-mpop-1.5.0/mpop/satin/helper_functions.py:126: RuntimeWarning: All-NaN axis encountered
  np.nanmin(y_dir),
/build/python-mpop-1.5.0/mpop/satin/helper_functions.py:127: RuntimeWarning: All-NaN slice encountered
  np.nanmax(x_dir),
/build/python-mpop-1.5.0/mpop/satin/helper_functions.py:128: RuntimeWarning: All-NaN slice encountered
  np.nanmax(y_dir)]
ok
```

**Comment by sebastic** [comment]
FTR: The regression patch in PROJ 5.0.0 also fixes the pyresample test failure:
{noformat}
======================================================================
FAIL: test_nearest_resize (pyresample.test.test_image.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyresample/test/test_image.py", line 151, in test_nearest_resize
    msg='ImageContainer resampling nearest neighbour failed')
AssertionError: 0.0 != 2212023.017583 within 7 places : ImageContainer resampling nearest neighbour failed

----------------------------------------------------------------------
{noformat}
